name: diffusion-acceleration-frontend
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8=hd037594_9
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - icu=78.2=h38cb7af_0
  - libexpat=2.7.4=hf6b4638_0
  - libffi=3.5.2=hcf2aa1b_0
  - liblzma=5.8.2=h8088a28_0
  - libsqlite=3.51.2=h1ae2325_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.6.1=hd24854e_1
  - packaging=26.0=pyhcf101f3_0
  - pip=26.0.1=pyh8b19718_0
  - python=3.12.12=h18782d2_2_cpython
  - readline=8.3=h46df422_0
  - setuptools=82.0.0=pyh332efcf_0
  - tk=8.6.13=h010d191_3
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.46.3=pyhd8ed1ab_0
  - pip:
      - aiofiles==24.1.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - brotli==1.2.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - fastapi==0.133.0
      - ffmpy==1.0.0
      - filelock==3.24.3
      - fsspec==2026.2.0
      - gradio==6.6.0
      - gradio-client==2.1.0
      - groovy==0.1.2
      - h11==0.16.0
      - hf-xet==1.3.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.4.1
      - idna==3.11
      - jinja2==3.1.6
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - numpy==2.4.2
      - orjson==3.11.7
      - pandas==3.0.1
      - pillow==12.1.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pygments==2.19.2
      - python-multipart==0.0.22
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.3.3
      - safehttpx==0.1.7
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - six==1.17.0
      - starlette==0.52.1
      - tomlkit==0.13.3
      - typer==0.24.1
      - typer-slim==0.24.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.3
      - uvicorn==0.41.0
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/diffusion-acceleration-frontend
